name: Build and test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3  # Use the actions/checkout@v2 action to check out the repository code

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Use the setup-node action to set up Node.js
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install  # Use the run action to execute 'yarn install'

      - name: Lint the Project
        working-directory: ./dockerlab/webapp
        run: yarn lint  # Use the run action to execute 'yarn lint'
