name: Build and test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 

      - name: Setup Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install  
      
      - name: Install ESLint Globally
        run: yarn global add eslint

      - name: Lint the Project
        working-directory: ./dockerlab/webapp
        run: yarn lint  

      - name: Build Docker Image
        run: |
          docker build -t alkdol/webapp:latest .
        working-directory: ./dockerlab/webapp