name: Build and test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3 

      - name: Setup Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install  
      
      - name: Install ESLint Globally
        run: yarn global add eslint

      - name: Lint the Project
        working-directory: ./dockerlab/webapp
        run: yarn lint  

      - name: Run Tests
        run: yarn test  
        working-directory: ./dockerlab/webapp

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          server: https://index.docker.io/v1/

      - name: Build & Push Docker Image
        run: |
          docker build -t alkdol/webapp:latest .
          docker push alkdol/webapp:latest
        working-directory: ./dockerlab/webapp